/**
 * S&P 500 constituents mirror — free, keyless, public-domain source.
 *
 * Source (live-verified 2026-08-02): github.com/datasets/s-and-p-500-companies, raw CSV at
 * data/constituents.csv. That repo's datapackage.json still declares license "ODC-PDDL-1.0"
 * (Open Data Commons Public Domain Dedication and License v1.0) and describes the data as
 * "sourced from Wikipedia [List of S&P 500 companies] ... updated daily" — in practice its
 * commit history shows real edits roughly every 1-3 weeks (whenever the index actually
 * changes), not a literal daily diff, which matches how rarely S&P 500 membership moves.
 * No auth, no rate-limit contract published; this is a static file served off GitHub's raw
 * CDN, so caching aggressively client-side is both correct (the list barely changes) and
 * polite (avoids hammering raw.githubusercontent.com on every scan).
 *
 * Confirmed live CSV header (2026-08-02):
 *   Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
 * We only use Symbol / Security / GICS Sector — the rest (sub-industry, HQ, date added, CIK,
 * founding year) aren't needed by anything in this codebase today; add fields here later if a
 * consumer needs them rather than guessing ahead of time.
 *
 * Source symbols use a dot for share classes (e.g. "BRK.B", "BF.B"); this repo's canonical
 * convention is a hyphen (see src/lib/sp500.ts's header comment and its "BRK-B"/"BF-B"
 * entries — the Robinhood order-symbol convention), so we normalize dot -> hyphen here to
 * match rather than surfacing a second, inconsistent symbol format.
 *
 * Honesty contract: a fetch failure, timeout, non-200, or unparseable/empty response returns
 * null — never a fabricated list, and never a stale cached list silently re-served past its
 * TTL and presented as current. There is currently no wired consumer of this module (see the
 * integration-pass notes for this round) — src/lib/sp500.ts's SP500_SYMBOLS is still a static
 * array generated by hand from Wikipedia on 2026-06-14, and nothing yet calls this file. It is
 * built as correct, tested infrastructure for a future refresh of that static list, not because
 * a live consumption point exists today.
 */

const SP500_CONSTITUENTS_URL =
  "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv";

export interface Sp500Constituent {
  symbol: string;
  name: string;
  sector?: string;
}

// This list changes only a handful of times per year (index committee additions/removals), so
// a full day of reuse is plenty and keeps us from re-fetching the same static file on every
// scan cycle. Env override left unclamped (like the other market-signals modules) — an operator
// raising or lowering it is an explicit decision.
const DEFAULT_TTL_MS = 24 * 60 * 60_000;
function sp500ConstituentsTtlMs(): number {
  const value = Number(process.env.SP500_CONSTITUENTS_CACHE_TTL_MS);
  return Number.isFinite(value) && value > 0 ? value : DEFAULT_TTL_MS;
}

let cache: { expiresAt: number; data: Sp500Constituent[] } | null = null;

/** Test helper: clear the in-process cache between runs. */
export function clearSp500ConstituentsCache(): void {
  cache = null;
}

/**
 * Split one CSV line into fields, honoring double-quoted fields that may themselves contain
 * commas (e.g. "Saint Paul, Minnesota" in the Headquarters Location column) and doubled-quote
 * escaping (`""` -> `"`). Pure / unit-tested.
 */
export function parseCsvLine(line: string): string[] {
  const fields: string[] = [];
  let current = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') {
          current += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        current += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ",") {
      fields.push(current);
      current = "";
    } else {
      current += ch;
    }
  }
  fields.push(current);
  return fields;
}

/** Source symbols use a dot for share classes; canonicalize to this repo's hyphen convention. */
function canonicalizeSymbol(raw: string): string {
  return raw.trim().toUpperCase().replace(/\./g, "-");
}

/**
 * Parse the datasets/s-and-p-500-companies constituents.csv text (header confirmed live
 * 2026-08-02: Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date
 * added,CIK,Founded) into constituents. Tolerates column reordering by locating columns by
 * name rather than fixed position. Returns [] for a header-only, empty, or unrecognized-header
 * (missing Symbol/Security) input — never throws. Pure / unit-tested.
 */
export function parseSp500ConstituentsCsv(csv: string): Sp500Constituent[] {
  const lines = csv.split(/\r?\n/).filter((line) => line.trim().length > 0);
  if (lines.length < 2) return [];

  const header = parseCsvLine(lines[0]).map((h) => h.trim());
  const symbolIdx = header.indexOf("Symbol");
  const nameIdx = header.indexOf("Security");
  const sectorIdx = header.indexOf("GICS Sector");
  if (symbolIdx < 0 || nameIdx < 0) return [];

  const out: Sp500Constituent[] = [];
  for (const line of lines.slice(1)) {
    const fields = parseCsvLine(line);
    const symbolRaw = fields[symbolIdx]?.trim();
    const nameRaw = fields[nameIdx]?.trim();
    if (!symbolRaw || !nameRaw) continue;

    const entry: Sp500Constituent = { symbol: canonicalizeSymbol(symbolRaw), name: nameRaw };
    const sectorRaw = sectorIdx >= 0 ? fields[sectorIdx]?.trim() : undefined;
    if (sectorRaw) entry.sector = sectorRaw;
    out.push(entry);
  }
  return out;
}

async function fetchSp500ConstituentsRaw(): Promise<Sp500Constituent[] | null> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);
  try {
    const res = await fetch(SP500_CONSTITUENTS_URL, {
      cache: "no-store",
      signal: controller.signal,
      headers: { accept: "text/csv" }
    });
    if (!res.ok) return null;
    const parsed = parseSp500ConstituentsCsv(await res.text());
    return parsed.length > 0 ? parsed : null;
  } catch {
    return null;
  } finally {
    clearTimeout(timeout);
  }
}

/**
 * Fetch the current S&P 500 constituent list (symbol, company name, GICS sector), keyless and
 * free, cached in-process for SP500_CONSTITUENTS_CACHE_TTL_MS (default 24h). Never fabricates:
 * a network error, timeout, non-200, or unparseable/empty response returns null. On failure we
 * do NOT fall back to a previously-cached (now-expired) list relabeled as current — null means
 * "ask again later", not "here is what we last saw."
 */
export async function fetchSp500Constituents(now: number = Date.now()): Promise<Sp500Constituent[] | null> {
  if (cache && cache.expiresAt > now) return cache.data;

  const data = await fetchSp500ConstituentsRaw();
  if (!data) return null;

  cache = { expiresAt: now + sp500ConstituentsTtlMs(), data };
  return data;
}
